/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/my-world.ts
 * Command: astryx theme build src/theme/my-world.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/// <reference path="./my-world.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const myWorldTheme: DefinedTheme;
